apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aster-policy
resources:
  - prometheus-configmap.yaml
  - prometheus-rules-configmap.yaml
  - prometheus-rbac.yaml
  - prometheus-pvc.yaml
  - prometheus-deployment.yaml
  - grafana-datasource-configmap.yaml
  - grafana-dashboard-configmap.yaml
  - grafana-pvc.yaml
  - grafana-deployment.yaml
  - policy-api-servicemonitor.yaml
