apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aster-policy
resources:
  - ../../base
patchesStrategicMerge:
  - patches/deployment.yaml
  - patches/hpa.yaml
commonLabels:
  environment: prod
