apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aster-policy
resources:
  - ../../base
  - ../../base/cert-manager/clusterissuer-http.yaml
  - cors-middleware.yaml
patchesStrategicMerge:
  - patches/deployment.yaml
  - patches/hpa.yaml
  - patches/ingress.yaml
commonLabels:
  environment: prod
images:
  - name: ghcr.io/aster-cloud/policy-api
    newTag: latest
