global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'dev'
    replica: 'prometheus-1'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - /etc/prometheus/rules/*.yml

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'policy-api'
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['policy-api:8080']
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'jvm_.*|http_.*|application_.*'
        action: keep

  - job_name: 'postgres'
    static_configs:
      - targets: ['aster-postgres-exporter:9187']

  - job_name: 'redis'
    static_configs:
      - targets: ['aster-redis-exporter:9121']
