apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: aster-policy
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/part-of: aster-platform
  annotations:
    app.kubernetes.io/component: database
    app.kubernetes.io/managed-by: kustomize
type: Opaque
stringData:
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: postgres
