apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: aster-policy
  labels:
    app: redis-exporter
    app.kubernetes.io/name: redis-exporter
    app.kubernetes.io/part-of: aster-platform
spec:
  type: ClusterIP
  selector:
    app: redis-exporter
  ports:
    - name: metrics
      port: 9121
      targetPort: metrics
