apiVersion: v1
kind: Service
metadata:
  name: policy-api
  namespace: aster-policy
  labels:
    app: policy-api
    app.kubernetes.io/name: policy-api
    app.kubernetes.io/part-of: aster-platform
spec:
  type: ClusterIP
  selector:
    app: policy-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
