apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: policy-api-ingress
  namespace: aster-policy
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
  labels:
    app: policy-api
    app.kubernetes.io/name: policy-api
    app.kubernetes.io/part-of: aster-platform
spec:
  rules:
    - host: policy-api.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: policy-api
                port:
                  number: 8080
